[general]
import = [
    # "~/.config/alacritty/themes/themes/papercolor_dark.toml",
    # "~/.config/alacritty/themes/themes/zenburn.toml",
    "~/.config/alacritty/themes/themes/solarized_light.toml",
]

[terminal.shell]

program = "/bin/zsh"
args = ["-l"]

[window]

padding = { x = 4, y = 0 }
opacity = 1.0

[window.dimensions]

columns = 120
lines = 32

[keyboard]

bindings = [
  # { key = "N", mods = "Control|Shift", action = "CreateNewWindow" }
]

[font]

size = 20
normal = { family = "MigMix 1M", style = "Regular" }
offset = { x = 0, y = -6 }
