ln -s "~/dotfiles/.vimrc"     "~/.vimrc" 
ln -s "~/dotfiles/.gvimrc"    "~/.gvimrc" 
ln -s "~/dotfiles/.latexmkrc" "~/.latexmkrc" 
ln -s "~/dotfiles/.vimperatorrc" "~/.vimperatorrc" 
ln -s "~/dotfiles/.inputrc" "~/.inputrc" 
